version: '3.8'

services:
  blog:
    image: esanchezdevel/yoprogramoenjava:v{BLOG_VERSION}
    container_name: yoprogramoenjava
    restart: always
    ports:
      - "3500:3500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/yoprogramoenjava
      - SPRING_DATASOURCE_USERNAME={DB_USER}
      - SPRING_DATASOURCE_PASSWORD={DB_PASS}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASS}
      - POSTGRES_DB=yoprogramoenjava
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: