version: '3.8'

services:
  blog:
    image: esanchezdevel/programandoconjava:{BLOG_VERSION}
    container_name: programandoconjava
    restart: always
    ports:
      - "443:3500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/programandoconjava
      - SPRING_DATASOURCE_USERNAME={DB_USER}
      - SPRING_DATASOURCE_PASSWORD={DB_PASS}
      - KEYSTORE_PASSWORD={HTTPS_KEYSTORE_PASSWORD}
    volumes:
      - /etc/letsencrypt/live/programandoconjava.com/keystore.p12:/certs/keystore.p12
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASS}
      - POSTGRES_DB=programandoconjava
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: