---
apiVersion: v1
kind: Service
metadata:
  name: yoprogramoenjava
spec:
  ports:
    - name: yoprogramoenjava
      port: 3500
      targetPort: 3500
  selector:
    app: yoprogramoenjava
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yoprogramoenjava-external
  labels:
    app: yoprogramoenjava
spec:
  type: NodePort
  ports:
    - port: 3500
      targetPort: 3500
      nodePort: 30001
  selector:
    app: yoprogramoenjava
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoprogramoenjava
  labels:
    app: yoprogramoenjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoprogramoenjava
  template:
    metadata:
      labels:
        app: yoprogramoenjava
    spec:
      containers:
        - name: yoprogramoenjava
          image: esanchezdevel/yoprogramoenjava:v0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: POSTGRES_DB
              value: "yoprogramoenjava"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
  selector:
    app: postgres