spring:
  application:
    name: programandoconjava

  datasource:
    url: jdbc:postgresql://postgres:5432/programandoconjava
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 3500
  error:
    whitelable:
      enabled: false