spring:
  application:
    name: programandoconjava

  datasource:
    url: jdbc:postgresql://postgres:5432/programandoconjava
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 3500
  error:
    whitelable:
      enabled: false
  ssl:
    key-store: /certs/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat

payments:
  paypal:
    client-id: ${SPRING_PAYPAL_CLIENT_ID}
    client-secret: ${SPRING_PAYPAL_CLIENT_SECRET}